env:
  CIRRUS_CLONE_DEPTH: "1"

eva_task:
  name: Eva build
  timeout_in: 120m
  container:
    image: fedora:rawhide
    cpu: 8
    memory: 8G
  setup_env_script:
    - dnf group install rpm-development-tools -y
    - dnf install gcc zip unzip bc bison dwarves elfutils-devel flex git-core grubby hostname kmod libkcapi-hmaccalc m4 net-tools openssl openssl-devel perl-Carp perl-devel perl-generators perl-interpreter python3-devel rsync -y
  build_script:
    - mkdir -p $HOME/rpmbuild/SOURCES rpm_output/
    - rpmbuild -v -bb --without install eva-kernel.spec
    - cp -av $HOME/rpmbuild/SRPMS/*.rpm rpm_output/
  artifacts:
    path: rpm_output/*
    when: always
    expire_in: 1 week
